---
openapi: 3.0.0
info:
   version: 1.3.0
   title: testfirst open api specification
   description: testfeature API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8005
     description: testfeature
tags:
- name: TestFirstEntity
- name: TestSecondEntity
paths:
   "/TestFirstEntity/get/search":
      get:
         tags:
         -  TestFirstEntity
         description: GpSearch
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/TestFirstEntity/{id}":
      delete:
         tags:
         -  TestFirstEntity
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  TestFirstEntity
         description: GpGetNounById
         parameters:
         -  in: "path"
            description: GpGetNounById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/TestFirstEntity":
      post:
         tags:
         -  TestFirstEntity
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/TestFirstEntity"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      TestFirstEntity:
         type: object
         properties:
            TestField1:
               type: "string"
               description: Description
            TestField2:
               type: "boolean"
               description: Description
      TestSecondEntity:
         type: object
         properties:
            TestAttribute1:
               type: "string"
               description: Description
            TestAttribute2:
               type: "date"
               description: Description